# site_name: "Water Scan AI Project to Identify Water Quality.

site_description: "Water Scan AI Project to Identify Water Quality"
site_author: "tralencar"
repo_name: "water_scan_ai_project"
repo_url: "https://github.com/tralencar/water_scan_ai_project"

plugins:
  - search
  - mkdocstrings:
      default_handler: python

site_name: Water Scan AI
site_url: https://tralencar.github.io/water_scan_ai_project/
theme:
  name: material
  palette:
    primary: orange
    scheme: slate
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  language: pt

nav:
  - ğŸ  Home: index.md
  - âš™ï¸ Installation: installation.md
  - ğŸš€ Project Usage: usage.md
  - ğŸ“‚ Project Structure: project_structure.md
  - ğŸ§  Methodology Used (CRISP-DM): crisp_dm_stages.md
  - ğŸ“¦ Modules:
      - ğŸ“¦ğŸ“‘ Overview: modules_index.md
      - ğŸ“¦ğŸ—ï¸ Main: module_1.md
      - ğŸ“¦ğŸ“ data_pipeline: module_2.md
      - ğŸ“¦ğŸ“œ mlflow_logger: module_3.md
      - ğŸ“¦ğŸ”„ model_registry: module_4.md
      - ğŸ“¦âš¡ model_trainer: module_5.md
      - ğŸ“¦ğŸŒ trainer_factory: module_6.md
  - ğŸ¤ Contribution: contributing.md
  - ğŸ§ª Tests: tests.md
  - ğŸ•°ï¸ Version History: changelog.md
